### PR TITLE
doc: Updated project status graph

### PR DESCRIPTION
**Pull request by alejandromd**
# Description
Updated the project status graph at week 9.

# Checklist:
- [x] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [x] I have checked that there is no fragile information published unintentionally.

# Screenshot:
image

### CODE REVIEW

**Review by alvgonfri — COMMENTED** [review]
The new graph looks correct, but I think #255 should be closed first so that the new changes are properly integrated into the new structure.

**Comment by alejandromd** [comment]
> The text size of the graphic should be larger so that it can be seen from the back of the class. Including the legend.

You are right, I forgot to increase the font size. I have already made the change

**Review by alvgonfri — APPROVED** [review]
The graph looks better now and it has been integrated in the new structure.

I'm assuming that the commit you made incluiding the theory pilll notes was a mistake. That will be reviewd in #274.

**Comment by alejandromd** [comment]
> The graph looks better now and it has been integrated in the new structure.
> 
> I'm assuming that the commit you made incluiding the theory pilll notes was a mistake. That will be reviewd in #274.

that's right, that commit should be in PR #274, but I was working late yesterday and had a headache, and got confused. Thanks for saying so

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
You should increase the size of the numbers in the graph, they are too small.

**Pull request merged**
