### PR TITLE
Doc/253 presentation and script 2

### PR DESCRIPTION
**Pull request by alvgonfri**
# Description
I have completed the slides (you can see them on Canva) and script for the April 9th ​​presentation. Please note the following things:

- Each paragraph is related to a different Canva slide.
- I haven't included the point "Justificar la replanificación del Sprint 2" because we are speaking about Sprint 3 now.
- I haven't included the point "Problemas -> Problema, solución, objetivo y métrica para analizar la calidad de la solución." because we don't have any problem registered in Sprint 3.
- I haven't included the point "Plan de pruebas (Pruebas de carga de back, tipos de tests realizados) -> Riesgos surgidos en base a eso con el respectivo análisis, etc" because the corresponding document is not completed yet.

# Checklist:
- [x] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [x] I have checked that there is no fragile information published unintentionally.

# Screenshot:
image

### CODE REVIEW

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
The problems section should be included if only to say that we have NOT registered any this week.

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
To make it easier to find each section, I recommend that you use the structure used last week, where for example we have a "Project Clock" section, instead of using such general sections as "Retrospective".

**Comment by alvgonfri** [comment]
- I have included a problem management section.
- I have included a test plan section.
- I have improved the script structure.

**Review by alvarobernal2412 — APPROVED** [review]
Thank you for your contibution!

**Pull request merged**
