### PR TITLE
doc: Add script first version

### LINKED ISSUE #470: Update PPTX and script
Update WPL presentation (Review the script and the feedback given in class).

### PR DESCRIPTION
**Pull request by alvarobernal2412**
# Description
PPTX script

# Checklist:
- [x] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [x] I have checked that there is no fragile information published unintentionally.

### CODE REVIEW

**Review by TunixR — APPROVED** [review]
I only accept it because it needs to be handed in.

**Comment by nicoloboo02** [comment]
La de poner un comentario en español cargandome el despliegue no te la viste venir @alvarobernal2412 :smiling_imp: :smiling_imp: :smiling_imp: 
no

**Review by alblopnov — APPROVED** [review]
First pr I've reviewed. It's never too late

**Comment by alvarobernal2412** [comment]
image

**Comment by TunixR** [comment]
Guys shut up. This PR has already been closed

**Comment by alblopnov** [comment]
> Guys shut up. This PR has already been closed

🤫

**Pull request merged**
