### PR TITLE
conf: Create stats script

### PR DESCRIPTION
**Pull request by alvarobernal2412**
# Description

- I have created a new workflow to update the github statistics automatically on a weekly basis.

# Checklist:
- [x] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [x] I have checked that there is no fragile information published unintentionally.

# Screenshots
Captura de pantalla 2024-03-08 a las 20 24 37

**Docusaurus locally deployed**
Captura de pantalla 2024-03-08 a las 20 37 05

### CODE REVIEW

**Comment by AntonioRodriguezRuiz** [comment]
It would be interesting to add _average_ stats as wells, such as average comments per issue or average comments per PR.

It would also be interesting to have a ranking of contributors and reviewers per week.

I would also add to the script some kind of analysis of new and updated documents in docusaurus over the week, I think it would somehow justify the usage of this tool as well

**Comment by alvarobernal2412** [comment]
Thanks for the advice, I think it looks really cool. Regarding docusaurus, do you have any idea how it could be done?

**Here are some pictures of how it looks like after the modification.**
Captura de pantalla 2024-03-09 a las 3 03 15
Captura de pantalla 2024-03-09 a las 3 03 25

**Comment by alejandromd** [comment]
thank you very much for your help, the statistics are very good|

**Comment by alvarobernal2412** [comment]
### If I am not mistaken, all the statistics are already automated, including the docusaurus change statistics. I hope you like them!!
Captura de pantalla 2024-03-10 a las 0 56 48

**Comment by alvarobernal2412** [comment]
## Steps to test this script locally:
1. Create a .env with a GitHub classic token called `ACCESS_TOKEN`.
2. Find the script in `src/components/stats/stats.mjs`.
3. Uncomment lines 3,5 and 7.
4. Comment lines 9-11.
5. Save the file.
6. Run in the terminal:
```bash
npm run update-stats
```
7. Then, run Docusaurus locally with:
- `npm run build`
- `npm run serve`

> [!warning]
> **IMPORTANT TO REMEMBER:**
> - **COMMENT THE LINES 3,5 AND 7**
> - **UNCOMMMENT LINES 9-11 AFTER TESTING IT**
> - **DISCARD THE CHANGES IN THE `Estadísticas de GitHub.mdx` FILE**

**Review by AntonioRodriguezRuiz — APPROVED** [review]
Looks good to me

**Pull request merged**
