### PR TITLE
Doc/288 update tco

### PR DESCRIPTION
**Pull request by Marchabar**
# Description
- Add GDPR in Capex, since it is a member of our company who is doing the job
- Add CM in Capex, since it is a member of our company who is doing the job
- Add social security costs for the remaining weeks of project development
- Update total TCO

# Checklist:
- [X] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [X] I have checked that there is no fragile information published unintentionally.

# Screenshot:
image
image

### CODE REVIEW

**Review by alvgonfri — COMMENTED** [review]
The changes look good, but I'm wondering this:

We are including personnel expenses in capex because they are internal personnel of the company, but when the remaining 5 weeks of the project are over, if we hire someone external, wouldn't it be considered opex? 

If this were the case, I think that the cost of personnel once the project finishes should be considered opex. In fact, the cost of the technician in charge of the SLA is still included in opex.

Maybe I'm wrong but I think it would be good to clarify this.

**Comment by Marchabar** [comment]
> The changes look good, but I'm wondering this:
> 
> We are including personnel expenses in capex because they are internal personnel of the company, but when the remaining 5 weeks of the project are over, if we hire someone external, wouldn't it be considered opex?
> 
> If this were the case, I think that the cost of personnel once the project finishes should be considered opex. In fact, the cost of the technician in charge of the SLA is still included in opex.
> 
> Maybe I'm wrong but I think it would be good to clarify this.

Nice, I have updated it!

**Review by alvgonfri — CHANGES_REQUESTED** [review]
It looks clearer now, but the excel called "TCO" has a small mistake and the total TCO is not being calculated correctly. You just have to include cell E15 in the SUM of cell E16.

**Comment by Marchabar** [comment]
> looks clearer now, but the excel called "TCO" has a small mistake and the total TCO is not being calculated correctly. You just have to include cell E15 in the SUM of cell E16 and update the total TCO number.

Fixed!

**Review by alvgonfri — APPROVED** [review]
Everything is well now!

**Pull request merged**
